{% set name = "oncopipe" %}
{% set version = "1.0.9" %}
{% set sha256 = "3f1c356b7c78c6ebec9a3634d712d6285ca95dae7f6f636566c40d3b55066f03" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LCR-BCCRC/lcr-modules/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: pushd oncopipe && python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - pyyaml
    - pandas
    - snakemake >=5.4,<5.19
  run:
    - python >=3.6
    - pyyaml
    - pandas
    - snakemake >=5.4,<5.19

test:
  imports:
    - oncopipe

about:
  home: https://github.com/LCR-BCCRC/lcr-modules
  doc_url: https://lcr-modules.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Functions for running Snakemake modules"

extra:
  recipe-maintainers:
    - acaprez
