{% set name = "busco" %}
{% set version = "4.1.0" %}
{% set sha256 = "d066869184dc48de677ee37bc520eca7c7c4f7f87b4c983e7de1103db120b2de" %}
{% set repo = "busco" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True  # [osx]
  number: 0
  linux-64: python

source:
  url: https://gitlab.com/ezlab/{{ repo }}/-/archive/{{ version }}/busco-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  host:
    - python >=3.3
    - pip
    - findutils
    - blast >=2.2,<2.4
    - hmmer >=3.1b2 # sepp needs this version
    - augustus
    - biopython
    - r-base
    - r-ggplot2 >=2.2.1
    - prodigal
    - sepp >=4.3.10
  run:
    - python >=3.3
    - findutils
    - blast >=2.2,<2.4
    - hmmer >=3.1b2 # sepp needs this version
    - augustus
    - biopython
    - r-base
    - r-ggplot2 >=2.2.1
    - prodigal
    - sepp >=4.3.10

test:
  requires:
    - wget
  commands:
    - busco -h
    - generate_plot.py -h


about:
  home: http://busco.ezlab.org/
  license: GPL
  summary: BUSCO provides measures for quantitative assessment of genome
           assembly, gene set, and transcriptome completeness based on
           evolutionarily informed expectations of gene content from
           near-universal single-copy orthologs selected from OrthoDB.

extra:
  identifiers:
    - biotools:busco
    - doi:10.1093/bioinformatics/btv351
  recipe-maintainers:
    - silask
    - matsepp
    - berkelem
