{% set version = "0.20.0" %}

package:
  name: unifrac
  version: {{ version }}

source:
  url: https://github.com/biocore/unifrac/archive/{{ version }}.tar.gz
  sha256: e2692c683fddc6450ca4da049112b00264cf61aef1071d2ebc0f0539b86611b8

build:
  number: 0
  skip: True # [py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - h5py 2.9.0
    - cython >=0.28.3
    - numpy >=1.12.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('h5py') }}
    - biom-format
    - scikit-bio >=0.5.1

test:
  imports:
    - unifrac
  commands:
    - ssu --help
    - faithpd --help
    - python -m unittest unifrac.tests.test_methods
    - python -m unittest unifrac.tests.test_api

about:
  home: https://github.com/biocore/unifrac
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Fast phylogenetic diversity calculations'

